### ISSUE TITLE
Disabling "Shift toggle Chinese Mode" makes duplicate punctuation

### ISSUE THREAD

**Issue by alone8172** [Cangjians/libcangjie#103]
## issue
The problem just like the title.
In setting --> Editing, uncheck "Shift toggle Chinese Mode".
Typing punctuation marks like ```：```, ```，```, ```。``` by holding shift and press the key.
There presents two punctuation marks that I type.
In action, that is: 
1. hold shift
2. press key <:>
3. ```：：``` present on screen

## my setting 
- Chi
- halt
![image](https://user-images.githubusercontent.com/29729024/32598067-aaa9bc68-c573-11e7-8908-43f33f3d37cf.png)
![image](https://user-images.githubusercontent.com/29729024/32598097-bfb4c4ae-c573-11e7-8f62-a753dfd8cbd8.png)
![image](https://user-images.githubusercontent.com/29729024/32598110-c89c26ca-c573-11e7-889c-c5872b713b21.png)

**Comment by bochecha** [comment]
Hi, the screenshots don't correspond to anything related to libcangjie or ibus-cangjie.

Are you sure you opened this bug report in the right place :)

**Comment by yookoala** [comment]
@alone8172  This is probably related to [ibus-table](https://github.com/acevery/ibus-table) and Cangjie in [ibus-table-chinese](https://github.com/definite/ibus-table-chinese), which are entirely different projects. Please report this issue there. Thanks.
