### ISSUE TITLE
Order of suggested characters (x disambiguation)

### ISSUE THREAD

**Issue by boyin** [Cangjians/libcangjie#55]
Both Cangjie3 and Cangjie5 have officially sanctioned "canonical characters" and "duplicate characters".  For each encoding that covers multiple characters, one character is selected to be the "canonical" character and is the default character selected by that sequence.  The other character(s) is selected by letter(s) X in prefix or suffix.  (Currently ibus-cangjie uses suffix X; ibus-table-chinese-cangjie, like MacOSX, uses prefix).

The following pairs of characters  seems to be listed the wrong way around in the default setup of ibus-cangjie (and ibus-table-chinese-cangjie) because they were arranged in what used to be known as "big-5 code order".

ABJJ\*   暈      XABJJ  暉  
AFMBC\*  顯      XAFMB\* 顥  
ANAU\*   晚      XANAU  冕  
AYK     旻      XAYK   旼  
BHN\*    肌      XBHN\*  冗  
BT\*     皿      XBT\*   冊  
BUOG\*   瞿      XBUOG  睢
DWD\*   棵        XDWD\*     梱
DYTJ\*   樟     XDYTJ    梓 
EA      汨      XEA    沓 XXEA    汩
HMNL\*   郵      XHMNL  邸
MRNO\*   歌      XMRNO  砍 
NL\*     引      XNL\*   弔  
NO\*     欠      XNO\*   久 
OFHAF   鷦      XOFHA  鷡  
OGE\*    雙      XOGE\*  隻  
ORMBC\*  頷      XORMB\* 頜  
QYBB    揥      XQYBB  撾
RMMR    跖      XRMMR  唔  
RSHAF   鶚      XRSHA  鴞  
SHOE\*   履      XSHOE  屐  
SRNL\*   郡      XSRNL  邵  
TMD\*    某      XTMD\*  芋  
TKN     荑      XTKN   艽  
TMNL    邯      XTMNL  鄞  
TW\*     苗      XTW\*   曲  
TWK\*    奠      XTWK\*  茵  
TSP     懃      XTSP   苨
VFHAF\*  鸞      XVFHA\* 鷥 
VFJMC\*  繽      XVFJM\* 縯  
 VFQ     攣      XVFQ      姅
WD\*     果      XWD\*   困  
YPD     柴      XYPD   迆  
YRPA\*   詢      XYRPA  詣  
YRU     訕      XYRU   乩  
YTHAF   鸕      XYTHA  鴗

**Comment by boyin** [comment]
Is anyone still here?

**Comment by bochecha** [comment]
> Is anyone still here?

I am. I haven't had much time to work on the *cangjie projects for some time, though.

**Comment by boyin** [comment]
Sorry about falling off the face of the earth; was depressed by many things and events.
Now I have to work on Cangjie in Fedora 24 since I haven't upgraded in two years (sniff).

**Comment by boyin** [comment]
So I should build my version of libcangjie (with X disambiguations according to canonical CJ), have them reviewed by someone and then submit a pull request?  Is that the correct idea?

**Comment by yookoala** [comment]
Please send us a pull request. And let's discuss the difference here afterwards. I think all the changes would be in [table.txt](https://github.com/Cangjians/libcangjie/blob/master/data/table.txt). Should be easy to follow.

I am a long time Cangjie 3 user and yet I don't use X-disambiguations at all. I wouldn't know what to expect there. But I would expect wildcard to carry on work as expected. I agree we should have a consistent behaviour on X-disambiguations mappings. Let's access if the changes are too much, or is there any work around on that.

We were pushing for a major format change in `table.txt` back in the 2014. Apparently we didn't have time to finish it. If code are ready to merge and that doesn't break other user expectations to this library, I think we can merge and make a new minor release.

**Comment by boyin** [comment]
I am still trying to compile libcangjie with my table.txt without errors on a newly installed Fedora 24.  Sorry for being slow.  If I keep having trouble I might have to ask you guys soon for help understand where the errors came from.

**Comment by boyin** [comment]
Hello, folx,

I have been running into this and I have not been able to isolate the problem, can someone perhaps point out something that is easy to miss that will make the program segfault?

[by@titania libcangjie]$ make
make  all-am
make[1]: Entering directory '/home/by/libcangjie'
  GEN      data/cangjie.db
/bin/sh: line 2: 18305 Segmentation fault      (core dumped) bin/libcangjie_dbbuilder data/table.txt data/cangjie.db > /dev/null
Makefile:1587: recipe for target 'data/cangjie.db' failed
make[1]: *** [data/cangjie.db] Error 139
make[1]: Leaving directory '/home/by/libcangjie'
Makefile:636: recipe for target 'all' failed
make: *** [all] Error 2

but all of the lines have 15 fields

 [by@titania libcangjie]$ awk "(NF!=15)" data/table.txt
# See the README.table.rst file in this folder for details about this data.

     
# SetSetting the frequency for this character when queried with 'hvpi' to 0
# allallows us to be more compatible with the default Cangjie input method on
# thathat "other Operating System" ;)
     
# Yes, we're using the word "SPACE" here to represent a space (' '). We can't
# simply use a space character directly as it's the column delimiter, so we
# have to be clever.

**Comment by boyin** [comment]
This is a (lack of) progress report.

I tried to edit my previous table.txt for libcangjie-1.1 to fit libcangjie-1.3 and kept getting errors.

I am now back to editing libcangjie-1.3's original table.txt file.

I apologize for my lack of talent in debugging.

**Comment by bochecha** [comment]
@boyin You don't need to constantly notify us that you didn't make any progress.

We're not your boss, there is no deadline, so we're just grateful you work on this, no matter how long it takes. :smiley: 

Keep doing things at your own pace, ask when you need help, and don't feel any pressure to somehow get it done quickly.

As for your segmentation fault, it's hard to help without seeing the code. Don't hesitate to push your work in progress somewhere and point us to it.

Thanks.

**Comment by boyin** [comment]
I am glad that I have a small progress report.  In my attached zip file, there is a new version of table.txt (t3a), a uniform diff file, and split of the diff file into (a) characters on my CJ3 duplicates list, (b) big5 characters which has X encoding added needlessly for conflicts with non-big5 characters, and (c) corresponding non-big5 characters which should receive a X encoding.

All 4- and 5-digit numbers are line numbers in the original table.txt file

 1. MISTAKE: CORRECTIONS / MISSING ENCODINGS

   7164 -xnem     丞      no other useful char with this encoding
   7165 +hgi      丟      else hgi and mgix go to different chars
                          mgi is neither Win's nor Mac's main encoding 
   7282 -ttx      井      mistake (CJ3 is always 井 tt, big5 order)
  10034 xyck      奕      reformat to comply with regular list form
  12315 -isbt     扁      conformity with MacOS/Win and solves problem with 盛
  15624 -jcegg    漥      mix-up with 窪 jcegg (also only big5 char at ejcg!)
  21172 -tyrv     蓑      mix-up, should always have tywv

Note the following pairs

  10095 xvis      妒(幻)          12318 isbt      扁(盛)

      the authors of table.txt have visx 妒 and isbtx 扁, but
      does not have the corresponding non-X form for CJ3.  Win
      and MacOS do not have vis for 妒 and isbt for 扁 period.

      I suspect that this is a mistake like mgi/hgi 丟.
      Since 幻 outranks 妒, this is not a problem, but xvis
      for 幻 is unneeded.  Since 扁 outranks 盛, this is a
      problem, and either we have to remove isbt from 扁 or
      add xisbt to 盛.  I chose the former.


 2. MISTAKE: SC/TC confusions

   7491 -omro   + omfm    佥(僉)
  11912 -gep    + gbhp    悫(愨)

 3. REMOVED EXTRA X ENCONDING FROM SOLE TC BIG5 CHAR
    Potentially useful non-big5 chars (marked "+") gets X encoding.

   7418 -xommi    伝     会+      15576 -xejpu    滵     浇+  
   7375 -xol      仲     个+      15636 -xedlo    漱     濑+
   7451 -xomfo    伾     佥+      16083 -xfbnd    烰     学+
   8147 -xvl      凵     丩+妕    16823 -xmgkl(d) 珔     臶 
   8188 -xbmln    刞     删+      17127 -xmgmv(n) 甄     珁 
   8228 -xiiln    剆     剗+      17374 -xkhpa    痻     狥 
   8535 -xnems(u) 巹     卺       17534 -xhaha(j) 皞     皡 
   9066 -xrypd    喍     嘑+      18924 -xhdlo    簌     籁 
  10481 -xvnum    嬔     嬎       19294 -xvfna(u) 絻     絶+
  10841 -xushi    屻     岃       19536 -xtbli    繭     萤+
  10919 -xhru     峊     乱+      19924 -xhjsm(m) 翱     翶+
  11019 -xuwjr    崮     崮崓     20216 -xbnau    脕     脃 
  11128 -xukcf    嶚     嶛       20418 -xbtis    臟     臓 
  11153 -xhku     嶴     岙       20609 -xtmon    芞     萮 
  11817 -xplmo    恌     愦+      20617 -xtoll    芥     养+
  12037 -xgep     愨     悫       21145 -xtvfh    蒶     𦯷䔋
  12099 -xikp     慦     龙+      21427 -xtbhu    藐     苋+
  12680 -xqsje    掫     摄+      22369 -xmub     襾     両 
  12854 -xqwli    擉     摆+      22428 -xbuho(k) 覹     矀 
  13044 -xqipd    攗     攈       22814 -xyrhd(n) 謻     誗 
  14254 -xdhaj    槔     槹       24627 -xcolb    鉓     鏅
  14525 -xdine    櫠     栐       24678 -xcyiu    銃     鋶 
  14894 -xepi     汋     沟+      24961 -xchwp    鎞     鏓 
  14947 -xenin    沀     汿+      26431 -xmkoi(v) 饜     饏   

5. CHARACTERS ON THE DUPLICATES LIST, there are two cases
    a) CJ3 and CJ5 X orders are reversed, I have changed them to CJ3 order 
        -- since in this version big5 ordering is used always.
    b) CJ5 order is the same as the CJ3 order, but at least 1 X encoding missing

[t3a.zip](https://github.com/Cangjians/libcangjie/files/633784/t3a.zip)

**Comment by boyin** [comment]
Ok, so that seems to be the extent of my editing, do any of you (meaning whoever is around) have any issues with the changes I propose? if not, I guess I will next find out and execute what is a pull request .....

**Comment by bochecha** [comment]
> do any of you (meaning whoever is around) have any issues with the changes I propose?

I'm afraid I don't really understand what you propose.

For example:

> 7164 -xnem 丞 no other useful char with this encoding

Ok, so... what should we do?

**Comment by boyin** [comment]
I am sorry I was a bit incoherent.

Because it was mentioned that table.txt was compiled from several sources and was the basis from which the current libcangjie was based, I tried to justify my changes.

Case 1 and 2, there seems to be a mistake or some corrections are in order
case 2 is a Simplified/Traditional confusion: the SC char got an encoding for the corresponding TC 
case 1 are the other changes I suggest and I commented on why these changes should be made

Case 3 are situations where there is an X encoding for a big-5 char, and the main reason is that there is a non-big-5 char with the same encoding.  Since big-5 chars take precedence in this and all prior versions of libcangjie, the X encoding is extraneous and I removed them.  In case this other non-big5 (usually SC) character is used with some frequency, I added X encodings for them.  [For 丞 NEM, no other char that is half-way reasonably useful has this encoding, so I classified that as simply a mistake.]

Case 4 involves duplicate characters both of which are known since Cangjie's big5-only days. There are (a) there is a missing (in my opinion) version 3 X encoding; (b) the version 5 X encoding is different from the version 3 encoding, which is done in big5 order.  Since this version of libcangjie only sorts in big5 order, I flipped the X and non-X encodings since otherwise the X encoding is useless; (c) both of the above.  

In cases 1-3, I Iisted all the characters concerned in each of my changes together with the line numbers.  Case 4 has so many characters that I decided not to list each and every one.

I am asking if any of you see any character about which the changes I propose is clearly wrong, because making a merge ("pull"?) request seems pointless if people will disagree with many of my suggested changes.

**Comment by boyin** [comment]
In the HEAD commit 61c7543674267127edee469211bfb0716808abc1 of boyin/libcangjie
now there are  three commits

1. fbd3e3c9 mistakes / corrections
2. f84064c5 X encodings not usually found in the duplicated char lists 
3. 61c75436 X encodings of chars usually found in the duplicated char lists

Please examine and see if you agree with my proposed changes.

**Comment by boyin** [comment]
Dear all, I must be doing something wrong, I keep pushing to 
https://github.com/boyin/libcangjie.git
and I enter the correct username and password, and it keeps saying everything is ok, but when I pull/clone the directory from another machine, I cannot get the 61c75436 commit ..........

**Comment by boyin** [comment]
I finally realized that git push -f must have screwed up everything.
I have deleted the repo, re-committed in three parts
fe3c6e8fda7 mistakes, corrections
d87e6a74ef extraneous x encodings for big5 chars, add them to corresponding simplified chars
b2e20829b fiddling around with x encodings on the original duplicates list
It is in boyin/libcangjie and I have refiled a pull request

**Comment by bochecha** [comment]
We have moved to Freedesktop: https://gitlab.freedesktop.org/cangjie/libcangjie

Please continue discussion there.
