### ISSUE TITLE
Suggested change / option: Z instead of * as wildcard for Jian-Yi / Simplified Cangjie / 簡易

### ISSUE THREAD

**Issue by boyin** [Cangjians/libcangjie#65]
Reason: 
1. I think that **z** is easier to access than asterisk *****.  I understand that on french keyboards, the natural result of hitting the "8 \* " key is the asterisk \* and not "8", but on most other keyboards \* requires a shift.
2. z is currently unused as a **non-leading** character in an encoding anyway.  There are encodings with z as the leading character for special symbols, but the wildcard _*_ does not operate in the leading position.
3. It seems incongruous for the asterisk \* to have different behavior from all other punctuation marks,

**Comment by bochecha** [comment]
We have moved to Freedesktop: https://gitlab.freedesktop.org/cangjie/libcangjie

Please continue discussion there.
